name: iOS_test
on: [push]

jobs:
  test_job:
    runs-on: macos-latest
    steps:
      - name: list simulators
        run: xcrun instruments -s
      - name: checkout
        uses: actions/checkout@v2
      - name: run test
        run: xcodebuild -project test.xcodeproj -scheme test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' clean test
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: test/artifacts/
